@startuml

left to right direction

package "Model" {
    class Client {
        - id : Long
        - name: String
        - email: String
        - phone: String
    }

    abstract class Account {
        - id: Long
        - number: String
        - balance: double
        + credit(amount: double): void
        + debit(amount: double): void
    }

    class CurrentAccount{
        - overdraftLimit: double
    }
    class SavingsAccount{
        - interestRate: double
    }

    class Operation {
        - id: Long
        - type: String
        - amount: double
        - date: Date
    }

    Client "1" -- "*" Account
    Account "1" -- "*" Operation
    CurrentAccount --|> Account
    SavingsAccount --|> Account
}

package DAO {
    class ClientDAO {
        + getAllClients(): List<Client>
        + findById(id: Long): Client
        + findByEmail(email: String): Client
    }

    class OperationDAO {
        + findAll(): List<Operation>
        + findByAccountId(accountId: Long): List<Operation>
        + save(operation: Operation): void
    }

    class AccountDAO {
            + findAll(): List<Account>
            + findById(id: Long): Account
            + findByNumber(number: String): Account
            + update(account: Account): void
        }
}

package Database{
    class DatabaseConnection {
        - {static} instance: DatabaseConnection
        + {static} getInstance(): DatabaseConnection
        + getConnection(): Connection
    }
}

package Factory{
    class AccountFactory {
        + createAccount(type: String): Account
    }
}

package Exception {
    class AccountNotFoundException{
    }
    class BusinessException{
    }
    class InsufficientBalanceException{
    }

    AccountNotFoundException --|> BusinessException
    InsufficientBalanceException --|> BusinessException
}

package DAO.Builder{
    class QueryBuilder{
    - query: StringBuilder
    - whereConditions: List<String>
    - orderByColumns: List<String>
    + {static} select(columns: String...): QueryBuilder
    + {static} insert(table: String): QueryBuilder
    + {static} update(table: String): QueryBuilder
    + {static} delete(): QueryBuilder
    + from(table: String): QueryBuilder
    + columns(columns: String...): QueryBuilder
    + values(count: int): QueryBuilder
    + set(columns: String...): QueryBuilder
    + where(condition: String): QueryBuilder
    + orderBy(columns: String...): QueryBuilder
    + build(): String
    }
}


package Service {
    class BankService {
        + deposit(accountNumber: String, amount: double): void
        + withdraw(accountNumber: String, amount: double): void
        + getAccountHistory(accountNumber: String): List<Operation>
    }
}

class ConsoleApp {
    + main(args: String[]): void
}

AccountFactory ..> Account
ClientDAO ..> DatabaseConnection
ClientDAO ..> Client
ClientDAO .> QueryBuilder
OperationDAO .> QueryBuilder
OperationDAO ..> DatabaseConnection
OperationDAO ..> Operation
AccountDAO ..> DatabaseConnection
AccountDAO ...> AccountFactory
AccountDAO .> QueryBuilder
BankService --> AccountDAO
BankService --> OperationDAO
ConsoleApp --> BankService
BankService .> AccountNotFoundException
BankService .> BusinessException
BankService .> InsufficientBalanceException

@enduml